Asm
Emgariko/first-term pull request #6
Opened 2020-06-28 19:08 UTC by Emgariko

2020-06-29 22:56 UTC, kt-cpp requested changes

2020-06-29 22:56 UTC, kt-cpp commented on asm/mul.asm
> +                cmp             r11, 1024
Нужно чтобы эта функция работала без хардкода, опираясь только на входные значения

2020-06-29 22:56 UTC, kt-cpp commented on asm/mul.asm
> +                add             [r14], rdx
[minor] Кажется carry в этом момент уже в `r15`. хоть это работает правильно при прочтении путает

2020-06-30 15:18 UTC, Emgariko commented on asm/mul.asm
> +                cmp             r11, 1024
fixed

2020-06-30 15:18 UTC, Emgariko commented on asm/mul.asm
> +                add             [r14], rdx
fixed

2020-06-30 16:03 UTC, kt-cpp approved these changes

2020-06-30 16:55 UTC, merged